### PR TITLE
Nuget trigger + XTrigger support correction

### PR DESCRIPTION
**Pull request by Greybird**
Hi,

Following Pull Request #9, here is a proposal to remove the xtrigger dependency, and provide actual xtrigger support (currently broken).

Regards,

Arnaud

### CODE REVIEW

**Comment by Greybird** [comment]
Would this be possible to merge this PR if you see no issue with it?
It would also make #9 outdated.
Thanks

**Comment by Greybird** [comment]
Hi,
Is the plugin still maintained ?

**Comment by Greybird** [comment]
Hi @imod and Happy Holidays,

Doing my unmerged PR EOY review.
Are you interested in this PR, or do you prefer me to close it ?

Thanks for your feedback!

**Comment by Greybird** [comment]
Hi @imod,

It's this time of the year again 😄 
Any chance to get your feedback ?

**Comment by imod** [comment]
@Greybird this plugin is open for adoption: https://plugins.jenkins.io/run-condition/

**Pull request merged**
