### PR TITLE
[JENKINS-19908] - Added "Environment variable exists" condition

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Resubmitted #10

https://issues.jenkins-ci.org/browse/JENKINS-19908

Signed-off-by: Oleg Nenashev nenashev@synopsys.com

### CODE REVIEW

**Comment by KostyaSha** [comment]
On first look is ok, do you still need it to be merged?

**Comment by KostyaSha** [comment]
@imod are you maintain this plugin?

**Comment by oleg-nenashev** [comment]
@KostyaSha, the answer is no. We had an e-mail discussion on this topic with @imod. I'll merge and release the change when somebody requests it or when I finish https://github.com/jenkinsci/run-condition-plugin/pull/12

**Comment by imod** [comment]
@KostyaSha as @oleg-nenashev says I'm not really the maintainer of this plugin and It would not be fair to have people waiting for me (as i'm already short in time for my own plugins). But if @oleg-nenashev does not find the time in the next week or so, then I will try to do my best...

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers I think this is still mergeable

**Pull request merged**
